# Dockerfile.scaler
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY custom_scaler.py .

EXPOSE 7000

CMD ["python", "custom_scaler.py"]
