---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-multiplier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-multiplier
  template:
    metadata:
      labels:
        app: matrix-multiplier
    spec:
      containers:
        - name: matrix-multiplier
          image: matrix-multiplier:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: matrix-multiplier-service
spec:
  selector:
    app: matrix-multiplier
  ports:
    - port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      serviceAccountName: custom-app-account
      containers:
        - name: custom-app
          image: custom-app:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-app-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: matrix-multiplier-scaler
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: matrix-multiplier-scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: matrix-multiplier-scaler
subjects:
  - kind: ServiceAccount
    name: custom-app-account
